# Generated by Django 5.2.6 on 2025-09-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decklist', models.TextField(blank=True, help_text='Lista de cartas do deck do jogador.')),
                ('status', models.CharField(default='Inscrito', max_length=50)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mesa', models.IntegerField()),
                ('time_vencedor', models.IntegerField(blank=True, help_text='1=Time 1, 2=Time 2, 0=Empate', null=True)),
                ('pontuacao_time_1', models.IntegerField(default=0, help_text='Placar do time 1 (ex: 2 vitórias parciais)')),
                ('pontuacao_time_2', models.IntegerField(default=0, help_text='Placar do time 2 (ex: 1 vitória parcial)')),
            ],
        ),
        migrations.CreateModel(
            name='MesaJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(help_text='1 ou 2, para definir a equipe do jogador na mesa.')),
            ],
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rodada', models.IntegerField()),
                ('status', models.CharField(default='Pendente', help_text='Ex: Pendente, Em Andamento, Finalizada', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Torneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('status', models.CharField(default='Aberto', help_text='Ex: Aberto, Em Andamento, Finalizado', max_length=50)),
                ('pontuacao_vitoria', models.IntegerField(default=3)),
                ('pontuacao_empate', models.IntegerField(default=1)),
                ('pontuacao_derrota', models.IntegerField(default=0)),
                ('pontuacao_bye', models.IntegerField(default=3)),
                ('quantidade_rodadas', models.IntegerField()),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
