# Generated by Django 5.2.6 on 2025-09-04 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('torneios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mesajogador',
            name='id_mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores_na_mesa', to='torneios.mesa'),
        ),
        migrations.AddField(
            model_name='mesajogador',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mesa',
            name='id_rodada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='torneios.rodada'),
        ),
        migrations.AddField(
            model_name='torneio',
            name='id_loja',
            field=models.ForeignKey(help_text='Usuário (loja) que criou o torneio.', on_delete=django.db.models.deletion.CASCADE, related_name='torneios_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rodada',
            name='id_torneio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rodadas', to='torneios.torneio'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='id_torneio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to='torneios.torneio'),
        ),
        migrations.AlterUniqueTogether(
            name='mesajogador',
            unique_together={('id_mesa', 'id_usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='rodada',
            unique_together={('id_torneio', 'numero_rodada')},
        ),
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together={('id_usuario', 'id_torneio')},
        ),
    ]
