# Generated by Django 5.2.6 on 2026-02-21 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RodadaJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True, help_text='Quando o jogador foi registrado no snapshot')),
                ('id_rodada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores_snapshot', to='torneios.rodada')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rodadas_participadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['id_rodada'], name='rodada_snapshot_idx')],
                'unique_together': {('id_rodada', 'id_usuario')},
            },
        ),
    ]
